version: '3.9'

services:
  redis:
    image: redis:5
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: always
    volumes:
      - db:/var/lib/mysql
  seeyau_backend:
    build: ./backend_api
    volumes:
      - ./backend_api:/usr/src/app
      - ./utility:/usr/src/app/utility
      - static:/static
      - certs:/etc/certs
    ports:
      - "3000:3000"
    entrypoint: ./deploy-entrypoint.sh
    depends_on:
      - db
      - redis
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      DEBUG: ${DEBUG}
      SECRET_KEY: ${SECRET_KEY}
      COMPOSE_DOMAIN_NAME: "backend"
      WAIT_FOR_IT_TIME: ${WAIT_FOR_IT_TIME}
      REDIS_HOST: "redis"
      DB_HOST: "db"
      KEYS_FOLDER: /etc/certs/${DOMAIN_NAME}
      DOMAIN_NAME: "192.168.1.105"
  nginx:
    build: ./nginx
    entrypoint: ./dev-entrypoint.sh
    volumes:
      - static:/static
      - certs:/etc/certs
      - ./utility:/utility
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - seeyau_backend
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
      KEYS_FOLDER: /etc/certs/${DOMAIN_NAME}
      WAIT_FOR_IT_TIME: ${WAIT_FOR_IT_TIME}
      BACKEND_ADDRESS: "seeyau_backend:8000"

volumes:
  db:
  static:
  certs:
