version: '3.9'

services:
  redis:
    image: redis:5
    ports:
      - "6379:6379"
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: always
    volumes:
      - db:/var/lib/mysql
  seeyau_backend:
    build: ./backend_api
    volumes:
      - ./backend_api:/usr/src/app
      - ./utility:/usr/src/app/utility
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      DEBUG: ${DEBUG}
      SECRET_KEY: ${SECRET_KEY}
      PUBLIC_HOST_IP: ${PUBLIC_HOST_IP}

volumes:
  db:
