version: '3.9'

services:
  redis:
    image: redis:5
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: always
    volumes:
      - db:/var/lib/mysql
  seeyau_backend:
    build: ./backend_api
    entrypoint: ["sh", "./deploy-entrypoint.sh"]
    volumes:
      - static:/usr/src/app/static
      - ./utility:/usr/src/app/utility
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      DEBUG: ${DEBUG}
      SECRET_KEY: ${SECRET_KEY}
      PUBLIC_HOST_IP: ${PUBLIC_HOST_IP}
  nginx:
    build: ./nginx
    volumes:
      - static:/static
      - certbot-conf:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - seeyau_backend
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
      KEYS_FOLDER: /etc/letsencrypt/live/${DOMAIN_NAME}/
  certbot:
    build: ./certbot
    volumes:
      - certbot-conf:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    environment:
      CERTBOT_EMAIL: ${CERTBOT_EMAIL}
      KEYS_FOLDER: /etc/letsencrypt/live/${DOMAIN_NAME}/
      DOMAIN_NAME: ${DOMAIN_NAME}
    depends_on:
      - nginx

volumes:
  db:
  static:
  certbot-conf:
  certbot-www:
