version: '3.9'

services:
  redis:
    image: redis:5
    ports:
      - "6379:6379"
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
  nginx:
    build: ./nginx
    entrypoint: ./dev-entrypoint.sh
    volumes:
      - ./backend_api/static:/static
      - ./backend_api/media:/media
      - certs:/etc/certs
      - ./utility:/utility
    ports:
      - "80:80"
      - "443:443"
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
      KEYS_FOLDER: /etc/certs/${DOMAIN_NAME}
      WAIT_FOR_IT_TIME: ${WAIT_FOR_IT_TIME}
      BACKEND_ADDRESS: "192.168.1.105:8000"

volumes:
  db:
  certs:
