version: '3.9'

services:
  redis:
    image: redis:5
    ports:
      - "6379:6379"
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: always
    volumes:
      - db:/var/lib/mysql
  seeyau_backend:
    build: .
    entrypoint: ["sh", "./deploy-entrypoint.sh"]
    volumes:
      - ./:/usr/src/app
      - static:/static
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      DEBUG: ${DEBUG}
      SECRET_KEY: ${SECRET_KEY}
      PUBLIC_HOST_IP: ${PUBLIC_HOST_IP}
  nginx:
    build: ./nginx
    volumes:
      - static:/static
      - certbot-conf:/etc/nginx/ssl
      - certbot-www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - seeyau_backend
      - certbot
    restart: unless-stopped
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
  certbot:
    image: certbot/certbot:v1.29.0
    volumes:
      - certbot-conf:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --keep-until-expiring --email "${CERTBOT_EMAIL}" --agree-tos --no-eff-email -d "${DOMAIN_NAME}"
    environment:
      CERTBOT_EMAIL: ${CERTBOT_EMAIL}
      DOMAIN_NAME: ${DOMAIN_NAME}

volumes:
  db:
  static:
  certbot-conf:
  certbot-www:
