# Generated by Django 4.1 on 2022-11-09 05:51

from django.db import migrations, models
import django.db.models.deletion
import utils.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('img_url', models.CharField(default='images/profile/blank.png', max_length=100)),
                ('last_seen', models.BigIntegerField(default=utils.utils.current_time_in_millis)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.BigIntegerField(default=utils.utils.current_time_in_millis)),
                ('is_liked', models.BooleanField(default=1)),
                ('who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked', to='profile.profile')),
                ('whom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='profile.profile')),
            ],
            options={
                'unique_together': {('who', 'whom')},
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_contact', models.BigIntegerField(default=utils.utils.current_time_in_millis)),
                ('is_mutual', models.BooleanField(default=0)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='profile.profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='profile.profile')),
            ],
            options={
                'unique_together': {('user', 'contact')},
            },
        ),
        migrations.CreateModel(
            name='BlackList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.BigIntegerField(default=utils.utils.current_time_in_millis)),
                ('is_active', models.BooleanField(default=1)),
                ('who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blacklist', to='profile.profile')),
                ('whom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_blacklist', to='profile.profile')),
            ],
            options={
                'unique_together': {('who', 'whom')},
            },
        ),
    ]
