# Generated by Django 4.1 on 2023-01-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='firebase_token',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
