# Generated by Django 4.1 on 2023-01-13 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_profile_firebase_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='firebase_token',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
    ]
