# Generated by Django 4.1 on 2023-02-10 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_alter_profile_firebase_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='firebase_token',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
