# Generated by Django 4.1 on 2022-10-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0004_alter_profile_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_mutual',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_seen',
            field=models.BigIntegerField(default=1665409446146),
        ),
    ]
