# Generated by Django 4.1 on 2022-09-16 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0004_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img_url',
            field=models.ImageField(default='blank_profile_image.jpg', upload_to='images/profile'),
        ),
    ]
