# Generated by Django 4.1 on 2022-09-16 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0005_alter_profile_img_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='img_url',
            new_name='pic',
        ),
    ]
