# Generated by Django 4.1 on 2022-10-19 14:08

from django.db import migrations, models
import django.db.models.deletion
import utils.utils


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0006_alter_profile_last_seen_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_seen',
            field=models.BigIntegerField(default=1666188502572),
        ),
        migrations.CreateModel(
            name='BlackList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.BigIntegerField(default=utils.utils.current_time_in_millis)),
                ('who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='black_list', to='profile.profile')),
                ('whom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_black_list', to='profile.profile')),
            ],
            options={
                'unique_together': {('who', 'whom')},
            },
        ),
    ]
