# Generated by Django 4.1 on 2022-09-17 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0007_alter_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='pic',
            new_name='img_url',
        ),
    ]
