# Generated by Django 4.1 on 2022-10-20 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0008_alter_blacklist_who_alter_blacklist_whom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_seen',
            field=models.BigIntegerField(default=1666250856114),
        ),
    ]
