# Generated by Django 4.1 on 2022-09-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0009_reset_profile_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img_url',
            field=models.CharField(default='images/profile/blank.png', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('user', 'contact')},
        ),
    ]
