# Generated by Django 4.1 on 2022-10-27 05:16

from django.db import migrations, models
import utils.utils


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0010_blacklist_is_active_alter_profile_last_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_seen',
            field=models.BigIntegerField(default=utils.utils.current_time_in_millis),
        ),
    ]
