# Generated by Django 4.1 on 2022-08-21 08:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatmessage_created_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='created_in',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
    ]
