# Generated by Django 4.1 on 2022-08-23 09:32

import chat.models.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_chatroom_users_alter_chatuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='created_in',
            field=models.BigIntegerField(default=chat.models.models.get_current_time),
        ),
    ]
