# Generated by Django 4.1 on 2022-08-24 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_chatuser_joined_in_alter_chatuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatuser',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatusers', to='chat.chatroom'),
        ),
    ]
