# Generated by Django 4.1 on 2022-08-25 12:10

from django.db import migrations, models
import utils.utils


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_alter_chatuser_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='created_in',
            field=models.BigIntegerField(default=utils.utils.current_time_in_millis),
        ),
        migrations.AlterField(
            model_name='chatuser',
            name='joined_in',
            field=models.BigIntegerField(default=utils.utils.current_time_in_millis),
        ),
    ]
