# Generated by Django 4.1 on 2022-08-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_chat_pull',
            field=models.BigIntegerField(default=0),
        ),
    ]
