# Generated by Django 4.1 on 2022-08-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_rename_user_id_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='user_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
