# Generated by Django 4.1 on 2022-08-24 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_profile_last_chat_pull'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='last_chat_pull',
        ),
    ]
