# Generated by Django 4.1 on 2022-09-20 08:44

import chat.models.models
from django.db import migrations, models
import django.db.models.deletion
import utils.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ChatUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_in', models.BigIntegerField(default=utils.utils.current_time_in_millis)),
                ('read_in', models.BigIntegerField(default=utils.utils.current_time_in_millis)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatusers', to='chat.chatroom')),
                ('user', models.ForeignKey(on_delete=models.SET(chat.models.models.get_sentinel_profile), to='profile.profile')),
            ],
        ),
        migrations.AddField(
            model_name='chatroom',
            name='users',
            field=models.ManyToManyField(related_name='chats', through='chat.ChatUser', to='profile.profile'),
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
                ('created_in', models.BigIntegerField(default=utils.utils.current_time_in_millis)),
                ('updated_in', models.BigIntegerField(default=utils.utils.current_time_in_millis)),
                ('author', models.ForeignKey(on_delete=models.SET(chat.models.models.get_sentinel_profile), related_name='messages', to='profile.profile')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatroom')),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends', to='profile.profile')),
                ('friend_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends_to', to='profile.profile')),
            ],
            options={
                'unique_together': {('friend', 'friend_to')},
            },
        ),
    ]
