# Generated by Django 4.1 on 2022-08-20 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends', to='profile.profile')),
                ('friend_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends_to', to='profile.profile')),
            ],
            options={
                'unique_together': {('friend', 'friend_to')},
            },
        ),
    ]
