# Generated by Django 4.1 on 2022-11-09 15:26

from django.db import migrations, models
import utils.utils


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='created_in',
            field=models.BigIntegerField(default=utils.utils.current_time_in_millis),
        ),
    ]
