# Generated by Django 4.1 on 2022-10-11 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0006_alter_profile_last_seen_like'),
        ('chat', '0002_alter_chatmessage_message'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chatuser',
            unique_together={('chat', 'user')},
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
