# Generated by Django 4.1 on 2022-11-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatroom_created_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='media_uri',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(default='plain', max_length=50),
        ),
    ]
