# Generated by Django 4.1 on 2022-11-26 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatmessage_media_uri_chatmessage_message_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="media_uri",
            field=models.CharField(blank=True, default=None, max_length=2000, null=True)
        ),
        migrations.RenameField(
            model_name='chatmessage',
            old_name='media_uri',
            new_name="extra"
        ),
    ]
