# Generated by Django 4.1 on 2022-08-21 08:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatroom_users_alter_chatuser_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='created_in',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
