# Generated by Django 4.1 on 2022-10-19 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatroom_is_active_chatroom_is_private'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='is_active',
        ),
    ]
