# Generated by Django 4.1 on 2023-02-10 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_extra_migrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='extra',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
