# Generated by Django 4.1 on 2022-09-15 11:20

import chat.models.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0004_contact'),
        ('chat', '0011_set_created_in_fields_to_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageReadBy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_in', models.BigIntegerField(default=1663240811995)),
            ],
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='read_by',
            field=models.ManyToManyField(through='chat.MessageReadBy', to='profile.profile'),
        ),
        migrations.AddField(
            model_name='messagereadby',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chatmessage'),
        ),
        migrations.AddField(
            model_name='messagereadby',
            name='who',
            field=models.ForeignKey(on_delete=models.SET(chat.models.models.get_sentinel_profile), to='profile.profile'),
        ),
    ]
