# Generated by Django 4.1 on 2022-09-15 11:40

from django.db import migrations, models
import utils.utils


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_messagereadby_chatmessage_read_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='updated_in',
            field=models.BigIntegerField(default=utils.utils.current_time_in_millis),
        ),
        migrations.AlterField(
            model_name='messagereadby',
            name='read_in',
            field=models.BigIntegerField(default=1663242053486),
        ),
    ]
