# Generated by Django 4.1 on 2022-09-15 15:10

from django.db import migrations, models
import utils.utils


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_chatmessage_updated_in_alter_messagereadby_read_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='read_by',
        ),
        migrations.AddField(
            model_name='chatuser',
            name='read_in',
            field=models.BigIntegerField(default=utils.utils.current_time_in_millis),
        ),
        migrations.DeleteModel(
            name='MessageReadBy',
        ),
    ]
